[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"

[build.environment]
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"

[[plugins]]
  # runs Cypress tests against the deployed URL
  package = "netlify-plugin-cypress"