export default {
  bodyBackground: 'var(--body-background)',
  primaryText: 'var(--primary-text)',
  sectionHeaderText: 'var(--section-header-text)',
  headerBackground: 'var(--header-background)',
  headerText: 'var(--header-text)',
  activeNavLink: 'var(--active-nav-link)',
  supplementalText: 'var(--supplemental-text)',
  inputBackground: 'var(--input-background)',
  inputBorder: 'var(--input-border)',
  inputDivider: 'var(--input-divider)',
  inputInnerLabel: 'var(--input-inner-label)',
  inputStaticText: 'var(--input-static-text)',
  focusUnderline: 'var(--focus-underline)',
  linkColor: 'var(--link-color)',
  kebabBorder: 'var(--kebab-border)',
  cardBackground: 'var(--card-background)',
  cardBorder: 'var(--card-border)',
  statusPassForeground: 'var(--status-pass-foreground)',
  statusPassBackground: 'var(--status-pass-background)',
  statusPassHeaderBackground: 'var(--status-pass-header-background)',
  statusFailForeground: 'var(--status-fail-foreground)',
  statusFailBackground: 'var(--status-fail-background)',
  statusFailHeaderBackground: 'var(--status-fail-header-background)',
  previewBorder: 'var(--preview-border)',
  themeButtonBackground: 'var(--theme-button-background)',
  decorativeBrackets: 'var(--decorative-brackets)',
}
