export const defaultTheme = {
  bodyBackground: 'var(--page-background)',
  primaryText: 'var(--gray700)',
  sectionHeaderText: 'var(--gray600)',
  headerBackground: 'var(--header-background)',
  headerText: 'var(--gray100)',
  activeNavLink: 'hsl(268, 28%, 46%)',
  supplementalText: 'var(--gray600)',
  inputBackground: 'white',
  inputBorder: 'var(--gray200)',
  inputDivider: 'var(--gray100)',
  inputInnerLabel: 'var(--gray500)',
  inputStaticText: 'var(--gray400)',
  focusUnderline: 'var(--pale-red)',
  linkColor: '-webkit-link',
  kebabBorder: 'var(--gray200)',
  cardBackground: 'white',
  cardBorder: 'var(--gray100)',
  statusPassForeground: 'var(--dark-green)',
  statusPassBackground: 'var(--light-green)',
  statusPassHeaderBackground: 'var(--extra-light-green)',
  statusFailForeground: 'var(--dark-red)',
  statusFailBackground: 'var(--light-red)',
  statusFailHeaderBackground: 'var(--extra-light-red)',
  previewBorder: 'var(--gray300)',
  themeButtonBackground: 'var(--gray200)',
  decorativeBrackets: 'var(--gray300)',
}

export const darkTheme = {
  ...defaultTheme,
  bodyBackground: 'var(--gray900)',
  primaryText: 'var(--gray100)',
  supplementalText: 'var(--gray200)',
  sectionHeaderText: 'var(--gray200)',
  inputBackground: 'hsl(268, 14%, 10%)',
  inputDivider: 'var(--gray600)',
  inputInnerLabel: 'var(--gray200)',
  inputBorder: 'var(--gray700)',
  inputStaticText: 'var(--gray300)',
  focusUnderline: 'hsl(358, 82%, 76%)',
  linkColor: 'var(--pale-red)',
  cardBackground: 'var(--gray800)',
  cardBorder: 'var(--gray700)',
  kebabBorder: 'var(--gray500)',
  statusPassForeground: 'var(--dark-green)',
  statusPassBackground: 'hsl(133, 48%, 78%)',
  statusPassHeaderBackground: 'hsl(133, 48%, 64%)',
  statusFailForeground: 'var(--dark-red)',
  statusFailBackground: 'hsl(358, 48%, 78%)',
  statusFailHeaderBackground: 'hsl(358, 48%, 64%)',
  previewBorder: 'var(--gray400)',
  themeButtonBackground: 'var(--gray700)',
  decorativeBrackets: 'var(--gray400)',
}
