name: Build and test

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    name: Check out and install dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - run: npm run build --if-present

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - run: npm run lint
      - run: npm test
